GET http://localhost:4000/api/members

###

GET http://localhost:4000/api/members/fRHFQpK4rG9tS09WMWCBo

###

POST http://localhost:4000/api/members
Content-Type: application/json

{
  "name": "tomas",
  "age": "34"
}

###

PUT  http://localhost:4000/api/members
Content-Type: application/json

{
  "name": "prutt",
  "age": "45"
}

###

DELETE  http://localhost:4000/api/members/3